### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [rust-windowing/android-rs-glue#134]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from Serde or another library before this would be possible?

**Comment by yoanlcq** [comment]
I tried to make the move in my fork of this repo, but couldn't because of our dependency on the `cargo` crate. It expects `Decodable` everywhere, [such as in this function](https://docs.rs/cargo/0.20.0/cargo/fn.call_main_without_stdin.html).  

Also it appears `cargo` doesn't have its own "Drop rustc-serialize dependency" issue. I would file one, but I believe it would be better to leave it to you @dtolnay.

Otherwise other dependencies (e.g `toml`) look ready.

**Comment by dtolnay** [comment]
Looks like this was fixed on June 13 in https://github.com/rust-lang/cargo/pull/4149 and the latest [`cargo`](https://crates.io/crates/cargo/0.20.0) release is July 20 but doesn't include the change. @alexcrichton what is going on?

**Comment by alexcrichton** [comment]
Oh we only publish the stable release of cargo, so I think the removal of rustc-serialize will go out in the next publication of cargo

**Comment by hcpl** [comment]
@yoanlcq now [this function](https://docs.rs/cargo/0.21.1/cargo/fn.call_main_without_stdin.html) uses `Deserialize`. Hope this unlocks you.

**Comment by yoanlcq** [comment]
Thanks for mentioning this ! I hope too, but it's been quite a while and I'll need to dive in once again to be sure.  
I'll see if it turns out okay - if it does I'll open a PR.

**Comment by mb64** [comment]
Fixed in #223.
