### ISSUE TITLE
Running Basic Example: failed to read `/glue/Cargo.toml`

### ISSUE THREAD

**Issue by JonErikDSuero** [rust-windowing/android-rs-glue#181]
Hi,

I'm trying to run the basic example. I did the following:

1.) `cd android-rs-glue/examples/basic`
2.) `docker run --rm -v "$(pwd):/root/src" -w /root/src tomaka/cargo-apk cargo apk build`

However, I'm getting this error:

```
Compiling android_native_app_glue.c
Compiling injected-glue
Compiling glue_obj
Compiling crate
error: failed to load source for a dependency on `android_glue`

Caused by:
  Unable to update file:///glue

Caused by:
  failed to read `/glue/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

Do you know which step(s) that I'm missing?

Thank you

**Comment by tjtelan** [comment]
The reason this is failing when using the `docker run` example is hidden in `Cargo.toml`.

This line is saying the `android_glue` dependency is located in an above path relative to the current directory.
https://github.com/tomaka/android-rs-glue/blob/1d095846a687f873b6aed7d62ee32bc5a062e534/examples/basic/Cargo.toml#L15

However, in the docker command, `-v "$(pwd):/root/src"` only mounts in the current directory. Which misses mounting in the `glue` directory, which lives two directory levels up.

---
I was able to get a successful build of the basic example in two different ways (with a slight detour to install a target in order to get past an error message... please ignore that part). In general, all of the examples will work with either of the following approaches.

1. Edit `Cargo.toml` to use the git path to `android-rs-glue`, instead of a relative path

```
[dependencies.android_glue]
git = "https://github.com/tomaka/android-rs-glue"
```

This was the command that built successfully for me:

```$ docker run --rm -v "$(pwd):/root/src" -w /root/src tomaka/cargo-apk bash -c "rustup target add i686-linux-android && cargo apk build"```

2. Modify the mount path, and the working dir to accomodate the relative path in Cargo.toml

This was the command that built successfully for me:

```$ docker run --rm -v "$(pwd)/../..:/root/src" -w /root/src/examples/basic tomaka/cargo-apk bash -c "rustup target add i686-linux-android && cargo apk build"```

**Comment by philip-alldredge** [comment]
I believe this has been adequately explained by @tjtelan . Can we close this issue? It is important to give docker access to the root of the repo when running and then change directory within the docker before building the example.
