### ISSUE TITLE
Unable to detect build tool version folder with symlink

### ISSUE THREAD

**Issue by Abdillah** [rust-windowing/android-rs-glue#255]
# Description
I download the build tools through NixOS package definition with build tools version folder (e.g. `28.0.3`) as symbolic link. I am open whether case like this will/won't be supported (since it is an edge case but that how NixOS done thing).

## Expected
Detect the build tools version and run.

## Actual

```
$ cargo apk build
error: Unable to determine build tools version
```

**Comment by Abdillah** [comment]
I am sorry if the pointed line actually not the culprit. CMIIW

**Comment by katyo** [comment]
It's really strange behavior because according to [docs](https://doc.rust-lang.org/std/fs/struct.Metadata.html#method.is_dir) metadata's `.is_dir()` should follow symlinks:
https://github.com/rust-windowing/android-rs-glue/blob/513b5c55b953491e19b9cca5192120bb7a60b265/cargo-apk/src/config.rs#L318-L321
I use **nixos** too and this issue also actual for me.
Can we introduce environment variable `BUILD_TOOL_VERSION` to force using specific version of a tools as a last resort in that case.

**Comment by katyo** [comment]
@Abdillah, which your filesystem where */nix/store* located?

**Comment by katyo** [comment]
It seems, actually `DirEntry's` metadata() actually doesn't follows symlinks.
See https://doc.rust-lang.org/std/fs/struct.DirEntry.html#method.metadata

**Comment by Abdillah** [comment]
> @Abdillah, which your filesystem where /nix/store located?

It's on default place.. 

> It seems, actually DirEntry's metadata() actually doesn't follows symlinks. See https://doc.rust-lang.org/std/fs/struct.DirEntry.html#method.metadata

Yes, additionally when it is a symlink, it doesn't know whether it linked to a file or folder which might require additional handling.

**Comment by katyo** [comment]
@Abdillah Can you test cargo apk from my pr? It should work as expected.

**Comment by Abdillah** [comment]
Ah, sure. I missed the PR

**Comment by katyo** [comment]
@goddessfreya this issue can be closed
